
name: Build on tag

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '15'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@worksbutnottested'
        always-auth: true

    - name: Download dependencies
      run: |
        npm install --ignore-scripts
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH}}

    - name: Install dependencies
      run: |
        npm rebuild && npm run prepare --if-present

    - name: Build & publish
      run: |
        npm run build
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH}}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
